name: animal_sounds
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.14.0
  firebase_admob: ^0.9.3
  toast: ^0.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/category/Mammals.jpg
    - assets/images/category/Birds.jpg
    - assets/images/category/Reptiles.jpg
    - assets/images/category/Arthropods.jpg

    - assets/images/mammals/cat.jpg
    - assets/images/mammals/dog.jpg
    - assets/images/mammals/horse.jpg
    - assets/images/mammals/lamb.jpg
    - assets/images/mammals/pig.jpg
    - assets/images/mammals/rhino.jpg

    - assets/audio/mammals/cat.mp3
    - assets/audio/mammals/dog.mp3
    - assets/audio/mammals/pig.mp3
    - assets/audio/mammals/lamb.wav
    - assets/audio/mammals/horse.wav
    - assets/audio/mammals/rhino.mp3

    - assets/images/birds/raven.jpg
    - assets/images/birds/redlori.jpg
    - assets/images/birds/redparrot.jpg
    - assets/images/birds/snowowl.jpg
    - assets/images/birds/sparrow.jpeg
    - assets/images/birds/woodpecker.jpg

    - assets/audio/birds/raven.mp3
    - assets/audio/birds/redlori.mp3
    - assets/audio/birds/redparrot.mp3
    - assets/audio/birds/snowowl.mp3
    - assets/audio/birds/sparrow.mp3
    - assets/audio/birds/woodpecker.mp3

    - assets/images/reptiles/alligator.jpg
    - assets/images/reptiles/argentiniantortoise.jpg
    - assets/images/reptiles/cobra.jpg
    - assets/images/reptiles/gecko.jpg
    - assets/images/reptiles/indiangharil.jpg
    - assets/images/reptiles/rattlesnake.jpg

    - assets/audio/reptiles/alligator.mp3
    - assets/audio/reptiles/argentiniantortoise.mp3
    - assets/audio/reptiles/cobra.mp3
    - assets/audio/reptiles/gecko.m4a
    - assets/audio/reptiles/indiangharil.m4a
    - assets/audio/reptiles/rattlesnake.mp3

    - assets/images/arthropods/bee.jpg
    - assets/images/arthropods/bumblebee.jpg
    - assets/images/arthropods/cicada.jpg
    - assets/images/arthropods/cockroach.jpg
    - assets/images/arthropods/crab.jpg
    - assets/images/arthropods/mosquito.jpg

    - assets/audio/arthropods/bee.m4a
    - assets/audio/arthropods/bumblebee.m4a
    - assets/audio/arthropods/cicada.m4a
    - assets/audio/arthropods/cockroach.m4a
    - assets/audio/arthropods/crab.m4a
    - assets/audio/arthropods/mosquito.m4a

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
